phq9 = {
    1: "Little interest or pleasure in doing things",
    2: "Feeling down, depressed, or hopeless",
    3: "Trouble falling or staying asleep, or sleeping too much",
    4: "Feeling tired or having little energy",
    5: "Poor appetite or overeating",
    6: "Feeling bad about yourself or that you are a failure or have let yourself or your family down",
    7: "Trouble concentrating on things, such as reading the newspaper or watching television",
    8: "Moving or speaking so slowly that other people could have noticed. Or the opposite being so figety or restless that you have been moving around a lot more than usual",
    9: "Thoughts that you would be better off dead, or of hurting yourself",
    "-" : "--",
    "score" : "4.9.14.19.27",
    "range" : "minimal.mild.moderate.moderately_severe.severe",
    "problem" : "depression",
    "points" : "0.1.2.3"
}

ghq_28_questions_gemini = {
    1: "Have you recently been getting annoyed or irritable with people?",
    2: "Have you recently been losing confidence in yourself?",
    3: "Have you recently been feeling worthless?",
    4: "Have you recently been feeling hopeless about the future?",
    5: "Have you recently been feeling restless or wound up?",
    6: "Have you recently been getting a feeling of panic or fear?",
    7: "Have you recently been feeling unable to stick to things?",
    8: "Have you recently been feeling lonely?",
    9: "Have you recently been getting upset or tearful?",
    10: "Have you recently been feeling so unhappy that you have been getting fed up with life?",
    11: "Have you recently been losing sleep over worry?",
    12: "Have you recently been getting so tired towards the end of the day that you have been getting irritable?",
    13: "Have you recently been getting headaches?",
    14: "Have you recently been getting indigestion?",
    15: "Have you recently been feeling dizzy?",
    16: "Have you recently been getting pains in your chest?",
    17: "Have you recently been getting short of breath?",
    18: "Have you recently been getting pains in your back?",
    19: "Have you recently been getting pains in your muscles?",
    20: "Have you recently been getting pains in your joints?",
    21: "Have you recently been feeling nauseous?",
    22: "Have you recently been getting sick at your stomach?",
    23: "Have you recently been getting constipation?",
    24: "Have you recently been getting diarrhoea?",
    25: "Have you recently been getting a feeling of pins and needles?",
    26: "Have you recently been getting a dry mouth?",
    27: "Have you recently been feeling dizzy or faint?",
    28: "Have you recently been getting a difficulty in passing water?",
    "-" : "--",
    "points" : "0.1.2.3",
    "score" : "6.15.30.45.60.75.85",
    "range" : "minimal.somewhat.mild.mild_moderate.moderate.moderately_severe.severe",
    "problem" : "general",
}


ghq_12_questions_awell = {
    1: "Over the past few weeks... Have you been able to concentrate well on what you were doing?",
    2: "Over the past few weeks... Have your worries made you lose a lot of sleep?",
    3: "ver the past few weeks... Have you felt that you are playing a useful role in life?",
    4: "Over the past few weeks... Have you felt capable of making decisions?",
    5: "Over the past few weeks... Have you felt constantly overwhelmed and stressed?",
    6: "Over the past few weeks... Have you had the feeling that you cannot overcome your difficulties?",
    7: "Over the past few weeks... Have you been able to enjoy your normal daily activities?",
    8: "Over the past few weeks... Have you been able to adequately cope with your problems?",
    9: "Over the past few weeks... Have you felt unhappy or depressed?",
    10: "Over the past few weeks... Have you lost confidence in yourself?",
    11: "Over the past few weeks... Have you thought that you are a person worthless?",
    12: "Over the past few weeks... Do you feel reasonably happy considering all the circumstances?",
    "-" : "--",
    "points" : "0.1.2.3",
    "score" : "4.9.15.23.29.37",
    "range" : "minimal.somewhat.mild.moderate.moderately_severe.severe",
    "problem" : "general",
}

physical_health_ques = {
    1: "Stomach pain",
    2: "Back pain",
    3: "Pain in your arms, legs, or joints (knees, hips etc.)",
    4: "(Women only) Menstrual cramps or other problems with your periods",
    5: "Headaches",
    6: "Chest pain",
    7: "Dizziness",
    8: "Fainting spells",
    9: "Feeling your heart pound or race",
    10: "Shortness of breath",
    11: "Pain or problems during sexual intercourse",
    12: "Constipation, loose bowels or diarrhoea",
    13: "Nausea, gas, or indigestion",
    14: "Feeling tired or having low energy",
    15: "Trouble sleeping",
    "-" : "--",
    "score" : "4.9.15.23.34.46",
    "points" : "0.1.2.3",
    "range" : "minimal.somewhat.mild.moderate.moderately_severe.severe",
    "problem" : "general",
}
